import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import AuthProvider from '/mongo/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'First Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <NavBar />
          <div className='margin-top'>
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
