import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import AuthProvider from '/mongo/AuthProvider'
// import './style.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'First Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-slate-950'>
      {/* <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300;400;600&display=swap" rel="stylesheet" /> */}
      <body>
        <AuthProvider className='layout'>
          <NavBar />
          <div className='min-h-[90.9vh]'>
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
