import './globals.css'
import NavBar from './_components/NavBar'
import AuthProvider from './_components/AuthProvider'
import Footer from './_components/Footer'


export const metadata = {
  title: "Student'media",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className="dark bg-gray-200 text-gray-950 dark:bg-slate-950 dark:text-white">
        <AuthProvider>
          <NavBar />
          <div className='min-h-[90.9vh]'>
            {children}
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
