import './globals.css'
import NavBar from './_components/NavBar'
import AuthProvider from './_components/AuthProvider'
import Footer from './_components/Footer'


export const metadata = {
  title: "Student'media",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className="dark bg-slate-200 text-gray-950 dark:bg-gray-950 dark:text-white">
        <AuthProvider>
          <NavBar />
          <div className='' style={{minHeight:"calc(100vh - 4rem)"}}>
            {children}
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
