export const CODER_CHANNEL_TOCKEN = "CODER-CHANNEL-JWT-TOCKEN";

export const TWO_FACTOR_AUTHENTICATION = "TWO-FACTOR-AUTHENTICATION"

export const TOCKEN_MAX_AGE = 60 * 60 * 24 * 10;  // in seconds -> 10 days